name: build
on: [push]
jobs:

  staticchecks:
    runs-on: ubuntu-latest
    name: Go static checks
    
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
    
    - name: Vet
      run: |
        go vet ./...
    
    - name: Staticcheck
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck -checks all ./...

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm, arm64, s390x]
        go: ['1.20']
      fail-fast: false  
    
    name: Go ${{ matrix.go }} ${{ matrix.goos }} ${{ matrix.goarch }} build
    
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: 6

    steps:
    
    - name: Install qemu-user
      run: |
        sudo apt-get update
        sudo apt-get -y install qemu-user

    - uses: actions/checkout@v3
    
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        
    - name: Build
      run: |
        go build -v ./...

    - name: Test
      run: |
        go test -v -short ./...    
        
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        go: ['1.20']
      fail-fast: false  
    
    name: Go ${{ matrix.go }} macOS
    
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        
    - name: Build
      run: |
        go build -v ./...

    - name: Test
      run: |
        go test -v -short ./...    

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        go: ['1.20']
      fail-fast: false  
    
    name: Go ${{ matrix.go }} Windows
    
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        
    - name: Build
      run: |
        go build -v ./...

    - name: Test
      run: |
        go test -v -short ./...    
